#!/usr/bin/env python3
"""Run the SerialTap power-path decks through LTspice and tabulate the results.

    ./run.py                 run every deck in this directory
    ./run.py rail-sag        run one deck (with or without the .cir suffix)
    ./run.py --keep-raw ...  keep the .raw waveforms for the LTspice GUI

LTspice's batch mode writes a UTF-16LE .log next to the netlist and prints
nothing useful to stdout, so this wrapper decodes the log, joins each .step
line to its .meas results, and writes a markdown table to results/<deck>.md.

A swept deck's .raw runs to tens of megabytes and none of it belongs in the
repo, so it is deleted once parsed. Pass --keep-raw when you actually want to
open the waveforms.

Stdlib only, and no dependency on anything outside this repo.
"""

import os
import re
import subprocess
import sys

LTSPICE = "/Applications/LTspice.app/Contents/MacOS/LTspice"
SIM_DIR = os.path.dirname(os.path.abspath(__file__))
RESULTS = os.path.join(SIM_DIR, "results")


def read_log(path):
    """LTspice writes UTF-16LE, sometimes without a BOM."""
    raw = open(path, "rb").read()
    try:
        return raw.decode("utf-16-le")
    except UnicodeDecodeError:
        return raw.replace(b"\x00", b"").decode("utf-8", "replace")


def parse(text):
    """-> (list of step-parameter dicts, {measurement: [value per step]}, notes)"""
    steps, meas, notes = [], {}, []
    name, rows = None, None

    for line in text.splitlines():
        s = line.strip()
        if s.startswith(".step "):
            steps.append(dict(re.findall(r"(\w+)=([-\d.eE+]+)", s)))
            continue
        if s.startswith("Measurement:"):
            if name:
                meas[name] = rows
            name, rows = s.split(":", 1)[1].strip(), []
            continue
        m = re.match(r"^(\w+):\s*[^=]+=\s*([-\d.eE+]+)", s)   # un-stepped form
        if m and not s.startswith("Measurement"):
            meas.setdefault(m.group(1), []).append(float(m.group(2)))
            continue
        if name is not None:
            m = re.match(r"^(\d+)\s+([-\d.eE+]+)", s)
            if m:
                rows.append(float(m.group(2)))
            elif s and not s.startswith("step"):
                if name:
                    meas[name] = rows
                name, rows = None, None
        if "FAIL" in s or "Error" in s or "WARNING" in s:
            notes.append(s)

    if name:
        meas[name] = rows
    return steps, meas, notes


def fmt(v):
    if v is None:
        return ""
    a = abs(v)
    if a and (a < 1e-3 or a >= 1e5):
        return "%.4g" % v
    return "%.4f" % v if a < 10 else "%.3f" % v


def table(steps, meas):
    names = list(meas)
    keys = list(steps[0]) if steps else []
    show_pass = "margin" in meas

    head = keys + names + (["ok"] if show_pass else [])
    out = ["| " + " | ".join(head) + " |",
           "|" + "|".join(["---"] * len(head)) + "|"]

    n = max([len(v) for v in meas.values()] + [len(steps), 1])
    for i in range(n):
        row = [steps[i].get(k, "") for k in keys] if i < len(steps) else [""] * len(keys)
        row += [fmt(meas[m][i]) if i < len(meas[m]) else "" for m in names]
        if show_pass:
            mg = meas["margin"][i] if i < len(meas["margin"]) else None
            row.append("yes" if (mg is not None and mg > 0) else "NO")
        out.append("| " + " | ".join(str(c) for c in row) + " |")
    return "\n".join(out)


def run(deck, keep_raw=False):
    cir = deck if deck.endswith(".cir") else deck + ".cir"
    path = os.path.join(SIM_DIR, cir)
    if not os.path.exists(path):
        sys.exit("no such deck: %s" % path)

    print("==> %s" % cir)
    subprocess.run([LTSPICE, "-b", path], cwd=SIM_DIR,
                   stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

    log = path[:-4] + ".log"
    if not os.path.exists(log):
        sys.exit("LTspice produced no log for %s" % cir)

    text = read_log(log)
    steps, meas, notes = parse(text)
    if not meas:
        print("    no measurements - check results/%s.log" % cir[:-4])

    os.makedirs(RESULTS, exist_ok=True)
    base = os.path.join(RESULTS, cir[:-4])
    open(base + ".log", "w").write(text)

    title = next((l.strip() for l in text.splitlines() if l.startswith("Circuit:")), cir)
    body = ["# %s" % cir[:-4], "",
            "Generated by `sim/run.py` - do not edit; re-run instead.", ""]
    if steps or meas:
        body += [table(steps, meas), ""]
    if notes:
        body += ["## Solver notes", ""] + ["- `%s`" % n for n in dict.fromkeys(notes)] + [""]
    open(base + ".md", "w").write("\n".join(body))

    if not keep_raw:
        for junk in (path[:-4] + ".raw", path[:-4] + ".op.raw"):
            if os.path.exists(junk):
                os.remove(junk)

    print("    %d step(s), %d measurement(s) -> results/%s.md"
          % (len(steps), len(meas), cir[:-4]))


if __name__ == "__main__":
    if not os.path.exists(LTSPICE):
        sys.exit("LTspice not found at %s" % LTSPICE)
    args = sys.argv[1:]
    keep_raw = "--keep-raw" in args
    decks = [a for a in args if not a.startswith("-")] or sorted(
        f for f in os.listdir(SIM_DIR) if f.endswith(".cir"))
    for d in decks:
        run(d, keep_raw)
